/*
  # Foundation Schema — Kerala Grocery UK

  Creates all core tables needed for the ecommerce platform:
  stores, categories, brands, products, store_categories, store_products,
  keralagroceries source table, orders, cart, user_profiles, banners,
  carousel_banners, homepage_sections, and supporting tables.

  This is a consolidated migration that builds the full schema from scratch.
*/

-- ============================================================
-- CORE LOOKUP TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS stores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  domain text,
  color text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  is_active boolean DEFAULT true,
  show_on_homepage boolean DEFAULT true,
  icon text,
  sort_order integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS brands (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  logo_url text,
  description text,
  show_on_homepage boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- PRODUCTS TABLE (with approval workflow columns)
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE NOT NULL,
  description text,
  short_description text,
  image_url text,
  image_main text,
  image_medium text,
  image_thumbnail text,
  image_large text,
  image_path text,
  enhanced_image_url text,
  category_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  brand_id uuid REFERENCES brands(id) ON DELETE SET NULL,
  price numeric(10,2) NOT NULL DEFAULT 0,
  original_price numeric(10,2),
  compare_price numeric(10,2),
  discount_percentage integer DEFAULT 0,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  is_deal boolean DEFAULT false,
  is_new_arrival boolean DEFAULT false,
  is_bestseller boolean DEFAULT false,
  is_hot_product boolean DEFAULT false,
  hot_product_expires_at timestamptz,
  sold_count integer DEFAULT 0,
  rating decimal(2,1) DEFAULT 4.5,
  review_count integer DEFAULT 0,
  -- Approval workflow
  approval_status text NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft', 'approved', 'rejected')),
  visibility_status boolean NOT NULL DEFAULT false,
  approved_at timestamptz,
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  last_sync_at timestamptz,
  -- SEO fields
  seo_title text,
  seo_description text,
  seo_keywords text,
  tags text[],
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- STORE PRODUCTS (junction table)
-- ============================================================

CREATE TABLE IF NOT EXISTS store_products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  name_override text,
  description_override text,
  price_override numeric(10,2),
  image_override text,
  image_cdn_url text,
  current_stock integer NOT NULL DEFAULT 0,
  stock_override integer,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(store_id, product_id)
);

-- ============================================================
-- STORE CATEGORIES
-- ============================================================

CREATE TABLE IF NOT EXISTS store_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  name text NOT NULL,
  slug text NOT NULL,
  color text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  central_id uuid REFERENCES categories(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- KERALAGROCERIES SOURCE TABLE (external product import)
-- ============================================================

CREATE TABLE IF NOT EXISTS keralagroceries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id uuid REFERENCES stores(id) ON DELETE CASCADE,
  product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  product_title text,
  brand text,
  category_name text,
  price numeric(10,2),
  qnty integer DEFAULT 0,
  product_description text,
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- CENTRAL INVENTORY
-- ============================================================

CREATE TABLE IF NOT EXISTS central_inventory (
  product_id uuid PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
  product_name text,
  stock_quantity integer NOT NULL DEFAULT 0,
  reserved_quantity integer NOT NULL DEFAULT 0,
  low_stock_threshold integer NOT NULL DEFAULT 10,
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- ORDERS
-- ============================================================

CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  store_id uuid REFERENCES stores(id) ON DELETE SET NULL,
  order_number text UNIQUE NOT NULL,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text NOT NULL,
  delivery_address text NOT NULL,
  delivery_city text NOT NULL,
  delivery_postcode text NOT NULL,
  subtotal decimal(10,2) NOT NULL DEFAULT 0,
  delivery_fee decimal(10,2) NOT NULL DEFAULT 0,
  total decimal(10,2) NOT NULL DEFAULT 0,
  payment_method text NOT NULL CHECK (payment_method IN ('paypal', 'card', 'wallet', 'cod')),
  payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  order_status text NOT NULL DEFAULT 'pending' CHECK (order_status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_reference text,
  notes text,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  product_image text,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price decimal(10,2) NOT NULL,
  total_price decimal(10,2) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- CART
-- ============================================================

CREATE TABLE IF NOT EXISTS cart (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, product_id)
);

-- ============================================================
-- USER PROFILES
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  phone text,
  phone_verified boolean DEFAULT false,
  name text,
  display_name text,
  avatar_url text,
  address text,
  city text,
  postcode text,
  preferred_channel text DEFAULT 'email',
  provider text DEFAULT 'email',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- USERS (legacy/duplicate for compatibility)
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  phone text,
  name text,
  address text,
  city text,
  postcode text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- BANNERS
-- ============================================================

CREATE TABLE IF NOT EXISTS banners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subtitle text,
  image_url text,
  cta_text text,
  cta_link text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS carousel_banners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subtitle text,
  image_url text,
  cta_text text,
  cta_link text DEFAULT '/products',
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- HOMEPAGE SECTIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS homepage_sections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  section_name text NOT NULL CHECK (
    section_name = ANY(ARRAY['offers','bestsellers','new_arrivals','trending','low_price','deals_for_you','promotions'])
    OR section_name ~ '^custom_[a-z][a-z0-9_]{1,48}$'
  ),
  display_name text NOT NULL,
  mode text NOT NULL DEFAULT 'auto' CHECK (mode IN ('manual','auto')),
  is_active boolean NOT NULL DEFAULT true,
  product_limit integer NOT NULL DEFAULT 20,
  label text,
  icon text,
  color text,
  store_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================
-- PROMOTIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS promotions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  image_url text,
  link_url text,
  badge_text text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','scheduled')),
  priority integer NOT NULL DEFAULT 0,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- ORDER NOTIFICATIONS LOG
-- ============================================================

CREATE TABLE IF NOT EXISTS order_notifications_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
  channel text,
  status text,
  sent_at timestamptz DEFAULT now()
);

-- ============================================================
-- ACCOUNT DELETION REQUESTS
-- ============================================================

CREATE TABLE IF NOT EXISTS account_deletion_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  reason text,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- WALLETS (for wallet payment)
-- ============================================================

CREATE TABLE IF NOT EXISTS wallets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  balance numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric(10,2) NOT NULL,
  type text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now()
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_is_deleted ON products(is_deleted);
CREATE INDEX IF NOT EXISTS idx_products_approval_status ON products(approval_status);
CREATE INDEX IF NOT EXISTS idx_products_visibility_status ON products(visibility_status);
CREATE INDEX IF NOT EXISTS idx_products_approval_visibility ON products(approval_status, visibility_status);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON products(is_featured) WHERE is_featured = true;
CREATE INDEX IF NOT EXISTS idx_products_is_deal ON products(is_deal) WHERE is_deal = true;
CREATE INDEX IF NOT EXISTS idx_store_products_store_id ON store_products(store_id);
CREATE INDEX IF NOT EXISTS idx_store_products_product_id ON store_products(product_id);
CREATE INDEX IF NOT EXISTS idx_store_products_is_active ON store_products(is_active);
CREATE INDEX IF NOT EXISTS idx_store_categories_store_id ON store_categories(store_id);
CREATE INDEX IF NOT EXISTS idx_keralagroceries_store_id ON keralagroceries(store_id);
CREATE INDEX IF NOT EXISTS idx_keralagroceries_product_id ON keralagroceries(product_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart(user_id);
CREATE INDEX IF NOT EXISTS idx_cart_product_id ON cart(product_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON user_profiles(email);
CREATE INDEX IF NOT EXISTS idx_carousel_banners_active_order ON carousel_banners(is_active, display_order);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE keralagroceries ENABLE ROW LEVEL SECURITY;
ALTER TABLE central_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE carousel_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE homepage_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_notifications_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_deletion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- is_admin HELPER FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  uid uuid;
BEGIN
  uid := auth.uid();
  IF uid IS NULL THEN RETURN false; END IF;
  RETURN EXISTS (
    SELECT 1 FROM auth.users
    WHERE id = uid AND (raw_app_meta_data->>'is_admin')::boolean = true
  );
END;
$$;

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- stores
CREATE POLICY "Public can read stores" ON stores FOR SELECT TO anon, authenticated USING (true);

-- categories
CREATE POLICY "Public can read categories" ON categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage categories" ON categories FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- brands
CREATE POLICY "Public can read brands" ON brands FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage brands" ON brands FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- products: storefront only sees approved+visible
CREATE POLICY "Anon can read approved visible products"
  ON products FOR SELECT TO anon
  USING (approval_status = 'approved' AND visibility_status = true AND is_active = true AND (is_deleted IS NULL OR is_deleted = false));

CREATE POLICY "Authenticated can read approved visible products"
  ON products FOR SELECT TO authenticated
  USING (approval_status = 'approved' AND visibility_status = true AND is_active = true AND (is_deleted IS NULL OR is_deleted = false));

CREATE POLICY "Admins can read all products"
  ON products FOR SELECT TO authenticated
  USING (is_admin());

CREATE POLICY "Admins can insert products"
  ON products FOR INSERT TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update products"
  ON products FOR UPDATE TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

-- store_products
CREATE POLICY "Anon can read active store_products"
  ON store_products FOR SELECT TO anon
  USING (is_active = true);

CREATE POLICY "Authenticated can read active store_products"
  ON store_products FOR SELECT TO authenticated
  USING (is_active = true);

CREATE POLICY "Admins can manage store_products"
  ON store_products FOR ALL TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

-- store_categories
CREATE POLICY "Public can read store_categories" ON store_categories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage store_categories" ON store_categories FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- keralagroceries
CREATE POLICY "Anon can read keralagroceries" ON keralagroceries FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage keralagroceries" ON keralagroceries FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- central_inventory
CREATE POLICY "Public can read central_inventory" ON central_inventory FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins can manage central_inventory" ON central_inventory FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- orders
CREATE POLICY "Users can view own orders" ON orders FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);
CREATE POLICY "Users can create orders" ON orders FOR INSERT TO authenticated WITH CHECK (user_id IS NULL OR user_id = (select auth.uid()));
CREATE POLICY "Anon can create orders" ON orders FOR INSERT TO anon WITH CHECK (user_id IS NULL);
CREATE POLICY "Users can update own orders" ON orders FOR UPDATE TO authenticated USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Admins can manage orders" ON orders FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- order_items
CREATE POLICY "Users can view own order items" ON order_items FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = (select auth.uid())));
CREATE POLICY "Anon can read order items" ON order_items FOR SELECT TO anon USING (true);
CREATE POLICY "Users can create order items" ON order_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Anon can create order items" ON order_items FOR INSERT TO anon WITH CHECK (true);

-- cart
CREATE POLICY "Users can read own cart" ON cart FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);
CREATE POLICY "Users can insert cart" ON cart FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Users can update cart" ON cart FOR UPDATE TO authenticated USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Users can delete cart" ON cart FOR DELETE TO authenticated USING ((select auth.uid()) = user_id);

-- user_profiles
CREATE POLICY "Users can read own profile" ON user_profiles FOR SELECT TO authenticated USING ((select auth.uid()) = id);
CREATE POLICY "Users can update own profile" ON user_profiles FOR UPDATE TO authenticated USING ((select auth.uid()) = id) WITH CHECK ((select auth.uid()) = id);
CREATE POLICY "Users can insert own profile" ON user_profiles FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = id);
CREATE POLICY "Admins can read all profiles" ON user_profiles FOR SELECT TO authenticated USING (is_admin());

-- users
CREATE POLICY "Users can read own user" ON users FOR SELECT TO authenticated USING ((select auth.uid()) = id);
CREATE POLICY "Users can update own user" ON users FOR UPDATE TO authenticated USING ((select auth.uid()) = id) WITH CHECK ((select auth.uid()) = id);
CREATE POLICY "Users can insert own user" ON users FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = id);

-- banners
CREATE POLICY "Public can read active banners" ON banners FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admins can manage banners" ON banners FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- carousel_banners
CREATE POLICY "Public can read active carousel banners" ON carousel_banners FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admins can manage carousel banners" ON carousel_banners FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- homepage_sections
CREATE POLICY "Public can read homepage sections" ON homepage_sections FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admins can manage homepage sections" ON homepage_sections FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- promotions
CREATE POLICY "Public can read active promotions" ON promotions FOR SELECT TO anon, authenticated USING (status = 'active');
CREATE POLICY "Admins can manage promotions" ON promotions FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- order_notifications_log
CREATE POLICY "Admins can manage notifications log" ON order_notifications_log FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- account_deletion_requests
CREATE POLICY "Users can insert deletion requests" ON account_deletion_requests FOR INSERT TO authenticated WITH CHECK ((select auth.uid()) = user_id);
CREATE POLICY "Admins can read deletion requests" ON account_deletion_requests FOR SELECT TO authenticated USING (is_admin());

-- wallets
CREATE POLICY "Users can view own wallet" ON wallets FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);
CREATE POLICY "Users can update own wallet" ON wallets FOR UPDATE TO authenticated USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);

-- transactions
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT TO authenticated USING ((select auth.uid()) = user_id);

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  date_part text;
  sequence_num integer;
BEGIN
  date_part := to_char(CURRENT_DATE, 'YYYYMMDD');
  SELECT COUNT(*) + 1 INTO sequence_num
  FROM orders WHERE order_number LIKE 'ORD-' || date_part || '-%';
  RETURN 'ORD-' || date_part || '-' || LPAD(sequence_num::text, 3, '0');
END;
$$;

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO user_profiles (id, email, phone, display_name, avatar_url, provider)
  VALUES (
    NEW.id, NEW.email, NEW.phone,
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.raw_user_meta_data->>'full_name', split_part(COALESCE(NEW.email,''), '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url',
    COALESCE(NEW.raw_app_meta_data->>'provider', 'email')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = COALESCE(EXCLUDED.email, user_profiles.email),
    phone = COALESCE(EXCLUDED.phone, user_profiles.phone),
    display_name = COALESCE(EXCLUDED.display_name, user_profiles.display_name),
    updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
CREATE TRIGGER update_orders_updated_at
  BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_cart_updated_at ON cart;
CREATE TRIGGER update_cart_updated_at
  BEFORE UPDATE ON cart FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- SEED DATA
-- ============================================================

-- Kerala Grocery UK store
INSERT INTO stores (id, name, slug, domain, color)
VALUES ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'Kerala Grocery UK', 'kerala-grocery-uk', 'keralagroceries.com', '#0B5D3B')
ON CONFLICT (id) DO NOTHING;

-- Homepage sections for Kerala store
INSERT INTO homepage_sections (store_id, section_name, display_name, mode, is_active, product_limit)
VALUES
  ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'trending', 'Trending Now', 'auto', true, 20),
  ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'bestsellers', 'Best Sellers', 'auto', true, 20),
  ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'new_arrivals', 'New Arrivals', 'auto', true, 20),
  ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'deals_for_you', 'Deals For You', 'auto', true, 20),
  ('a2e4d9f9-6b51-4071-97eb-decf72485b5a', 'promotions', 'Current Offers', 'manual', true, 20)
ON CONFLICT DO NOTHING;
